# Generated by Django 2.2.4 on 2020-02-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.Country')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SHR', 'Share'), ('CMM', 'Commodity'), ('ETF', 'Exchange Trade Funds'), ('CFD', 'Contract for difference'), ('IDX', 'Hypothetical portfolio of investment holdings which         represents a segment of the financial market'), ('CRYPTO', 'Crypto currencies'), ('FX', 'Marketplace for a various national currencies')], default='SHR', max_length=10)),
                ('date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.Share')),
            ],
        ),
    ]
