# Generated by Django 2.2.4 on 2020-02-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockprice',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='dailystockprice',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='dailystockprice',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='dailystockprice',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True),
        ),
    ]
